#!/bin/bash
gunzip -v -t './Download/Leptosporangiate Monilophytes//AFPO-SOAPdenovo-Trans-assembly.fa.gz'
gunzip -v -t './Download/Leptosporangiate Monilophytes//AFPO-translated-nucleotides.fa.gz'
gunzip -v -t './Download/Leptosporangiate Monilophytes//AFPO-translated-protein.fa.gz'
gunzip -v -t './Download/Green Algae//AZZW-SOAPdenovo-Trans-assembly.fa.gz'
gunzip -v -t './Download/Green Algae//AZZW-translated-nucleotides.fa.gz'
gunzip -v -t './Download/Green Algae//AZZW-translated-protein.fa.gz'
gunzip -v -t './Download/Eusporangiate Monilophytes//NHCM-SOAPdenovo-Trans-assembly.fa.gz'
gunzip -v -t './Download/Eusporangiate Monilophytes//NHCM-translated-nucleotides.fa.gz'
gunzip -v -t './Download/Eusporangiate Monilophytes//NHCM-translated-protein.fa.gz'
gunzip -v -t './Download/Mosses//WOGB-SOAPdenovo-Trans-assembly.fa.gz'
gunzip -v -t './Download/Mosses//WOGB-translated-nucleotides.fa.gz'
gunzip -v -t './Download/Mosses//WOGB-translated-protein.fa.gz'
